### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
For your [RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2091) (the bot complained Fastlane is missing). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this – e.g. moving the screenshots in to `fastlane/metadata/android/en-US/images/phoneScreenshots/` from their current location in `screenshots/`).

### CODE REVIEW

**Comment by licaon-kter** [comment]
@IzzySoft Maybe you need to rebase?

**Comment by IzzySoft** [comment]
Huh? What happened there? I just did a fresh fork & clone and then branched off of HEAD. Gosh, don't say your files use Windows formatting and my client converted them to Linux, then thought they're changed and need to be committed? Nope: the diff says I added new files and changed others which I didn't change, very strange… OK, let me try a rebase.

**Comment by licaon-kter** [comment]
Don't forget my PR in your repo :)

**Comment by IzzySoft** [comment]
No ideas what happened there, but pulling from master causes merge conflicts. Guess I'll have to start over with a new fork – no idea what's going on here. Or I just attach you the files and you add them yourself if it doesn't work out the other way.

**Comment by IzzySoft** [comment]
No conflicts (yet!) with the new one. Can you please merge before things go weird again? :wink:

**Comment by IzzySoft** [comment]
@licaon-kter amended that manually to #7 (no time to fiddle with transfer between 2 PRs, sorry – but credits are given in the commit message)

**Pull request closed without merging**
