### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
see #6 (please merge before you do other changes :wink: – before the same thing happens again. Currently it looks "clean")

### CODE REVIEW

**Comment by licaon-kter** [comment]
Any blockers @adityar224 ?

**Comment by IzzySoft** [comment]
@adityar224 May I ask what keeps you from merging? Anything wrong? Would be nice if you could process this. Or at least drop a note why you don't.

**Comment by adityar224** [comment]
Hey Locally I've had made few changes and haven't pushed the code yet. I'll merge as soon as it is ready. It would be great if you included the actual icon. Sorry for the huge delay xD.

**Comment by IzzySoft** [comment]
Just replace the icon with the one you want there – I only picked what I found :wink:

**Comment by IzzySoft** [comment]
Is there any chance this will get merged? I'll drop my fork soon (cleanup session)…

**Comment by adityar224** [comment]
Hey I am planning to deploy this in the Play Store, So for now I am dropping the plan to deploy this in F-droid. Sorry for the inconvenience.

**Comment by IzzySoft** [comment]
And you're aware of `fastlane deploy` would have done that job for you – based on what this PR provided? :wink: You'd then just have to add the fastlane binaries.

But I won't press. Thanks for taking the time to consider! I'll wait a little in case you change your mind (after checking `fastlane deploy`), and if not I'll just drop my fork. All the best for future development then!

**Comment by adityar224** [comment]
@IzzySoft @licaon-kter Have pushed a new commit along with the fastlane structure.

**Pull request closed without merging**
